
package co.com.rest.clientsoap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmpleadoService", targetNamespace = "http://service.empleado.war.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmpleadoService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.HelloResponse")
    @Action(input = "http://service.empleado.war.com.co/EmpleadoService/helloRequest", output = "http://service.empleado.war.com.co/EmpleadoService/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearEmpleado", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.CrearEmpleado")
    @ResponseWrapper(localName = "crearEmpleadoResponse", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.CrearEmpleadoResponse")
    @Action(input = "http://service.empleado.war.com.co/EmpleadoService/crearEmpleadoRequest", output = "http://service.empleado.war.com.co/EmpleadoService/crearEmpleadoResponse")
    public String crearEmpleado(
        @WebParam(name = "arg0", targetNamespace = "")
        Empelado arg0);

    /**
     * 
     * @return
     *     returns java.util.List<co.com.rest.clientsoap.Empelado>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarEmpleados", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.ListarEmpleados")
    @ResponseWrapper(localName = "listarEmpleadosResponse", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.ListarEmpleadosResponse")
    @Action(input = "http://service.empleado.war.com.co/EmpleadoService/listarEmpleadosRequest", output = "http://service.empleado.war.com.co/EmpleadoService/listarEmpleadosResponse")
    public List<Empelado> listarEmpleados();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarEmpleado", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.EliminarEmpleado")
    @ResponseWrapper(localName = "eliminarEmpleadoResponse", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.EliminarEmpleadoResponse")
    @Action(input = "http://service.empleado.war.com.co/EmpleadoService/eliminarEmpleadoRequest", output = "http://service.empleado.war.com.co/EmpleadoService/eliminarEmpleadoResponse")
    public String eliminarEmpleado(
        @WebParam(name = "arg0", targetNamespace = "")
        Empelado arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editarEmpleado", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.EditarEmpleado")
    @ResponseWrapper(localName = "editarEmpleadoResponse", targetNamespace = "http://service.empleado.war.com.co/", className = "co.com.rest.clientsoap.EditarEmpleadoResponse")
    @Action(input = "http://service.empleado.war.com.co/EmpleadoService/editarEmpleadoRequest", output = "http://service.empleado.war.com.co/EmpleadoService/editarEmpleadoResponse")
    public String editarEmpleado(
        @WebParam(name = "arg0", targetNamespace = "")
        Empelado arg0);

}
